---
# Configure Search Head Cluster

- name: SH Cluster
  debug: msg="Configuring Search Head Cluster...."

- name: /opt/splunk permissions
  file: path=/opt/splunk state=directory mode=0755 owner=splunk group=splunk recurse=yes

- name: start Splunk 
  service: name=splunk state=started

- name: search head init
  shell: splunk init shcluster-config -auth admin:{{ admin_pw }} \
          -mgmt_uri "https://{{ ansible_fqdn }}:8089" \
          -replication_port 8090 \
          -conf_deploy_fetch_url https://{{ groups['deployer'][0] }}:8089 \
          -secret {{ cluster['secret'] }} \
          -shcluster_label {{ cluster['label']['shc'] }}

- name: stop Splunk 
  service: name=splunk state=stopped

- name: restart Splunk
  include: "{{ playbook_dir }}/roles/base/tasks/restart.yaml"

- name: Configure Captain 
  shell: "splunk bootstrap shcluster-captain -servers_list {{ groups['search_head'] | map('regex_replace', '(.*)', 'https://\\1:8089') | join(',') }} -auth admin:{{ admin_pw }}"
  when: ansible_fqdn == "{{ groups['search_head'][0] }}"

- name: Integrate with IDX cluster
  shell: "splunk edit cluster-config -mode searchhead -master_uri https://{{ groups['master'][0] }}:8089 -auth admin:{{ admin_pw }} -secret {{ cluster['secret'] }}"

- name: restart Splunk
  include: "{{ playbook_dir }}/roles/base/tasks/restart.yaml"

