---
- hosts: all
  tasks:
    - name: include vars
      include_vars: "config.yaml"


# Start the Engines!
- include: playbooks/01_master_IDX.yaml
- include: playbooks/02_cluster_IDX.yaml
- include: playbooks/03_deployer_SHC.yaml
- include: playbooks/04_cluster_SHC.yaml
- include: playbooks/05_final.yaml
