# TEST

- hosts: master
  become_user: root
  become: true
  gather_facts: true

  tasks:
    - name: Add SearchHeads to IDX Master   
      command: "/usr/bin/splunk add search-server https://{{ item }}:8089  -auth admin:{{ admin_pw }} -remoteUsername admin -remotePassword {{ admin_pw }}"
      with_items: "{{ groups['search_head'] }}"
      ignore_errors: false

    - name: restart Splunk
      include: "{{ playbook_dir }}/roles/base/tasks/restart.yaml"
