# TEST

- hosts: master
  become_user: root
  become: true
  gather_facts: true

  tasks:
    - name: TEST
      debug: msg="THIS IS A TEST"

    - name: configure shcluster
      blockinfile: 
        path: /opt/splunk/etc/system/local/server.conf
        insertafter: EOF
        marker: ' '
        block: |
          [license]
          master_uri = https://{{ cluster['indexer']['master']['ip'] }}:8089
          
          [shclustering]
          pass4SymmKey = {{ cluster['secret'] }}
          shcluster_label = {{ cluster['search_head']['label'] }}
    # - name: TEST    
    #   command: "/usr/bin/splunk add search-server -host {{ item.value }}:8089  -auth admin:{{ admin_pw }} -remoteUsername admin -remotePassword {{ admin_pw }}"
    #   with_dict: "{{ cluster.search_head.members }}"
    #   ignore_errors: false
  
     


